version: '3.7'

services:
  {name}:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: cdi 
    #           device_ids:
    #             - nvidia.com/gpu=all
    #           capabilities: [gpu]
